btcrecover and parmawallet

diff --git a/src/btcrecover/Dockerfile b/src/btcrecover/Dockerfile
--- a/src/btcrecover/Dockerfile
+++ b/src/btcrecover/Dockerfile
@@ -1,15 +1,15 @@
-# Builds a container to run cryptography functions
-# For btcrecover ... includes python3-tk
-# All cpu cores from the host are available unless limited by a docker run command options: --cpus n, where n is a number
-
 FROM debian:latest
 RUN apt-get update -y && apt-get upgrade -y
 RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
                sudo vim nano libgmp-dev python3 python3-dev python3-pip openssl \
-               git python3-bitcoinlib python3-base58 \
+               procps gnupg tree htop \
+               git pip python3-cryptography python3-setuptools python3-bitcoinlib python3-base58 \
                python3-tk build-essential libssl-dev\
                locales \
+               python3-pyqt5 libsecp256k1-dev  \
+               --fix-missing
         && apt clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
+
 
 RUN pip3 install bech32 --break-system-packages
 RUN pip3 install base58 --break-system-packages
@@ -43,8 +43,25 @@ RUN locale-gen
 USER parman
 WORKDIR /home/parman
 RUN git clone --depth 1 https://github.com/3rdIteration/btcrecover.git
+
+RUN mkdir -p /home/parman/electrum_pip
+WORKDIR /home/parman/electrum_pip
+RUN curl -LO https://download.electrum.org/4.5.5/Electrum-4.5.5.tar.gz
+RUN curl -LO https://download.electrum.org/4.5.5/Electrum-4.5.5.tar.gz.asc
+RUN curl -LO https://raw.githubusercontent.com/spesmilo/electrum/master/pubkeys/ThomasV.asc 
+RUN gpg --import ThomasV.asc
+RUN if ! gpg --verify Electrum-4.5.5.tar.gz.asc 2>&1 | grep -qi good ; then \
+         echo "gpg verification failed" ; \
+         exit 1 ; \
+    fi
+RUN python3 -m pip install --user Electrum-4.5.5.tar.gz || \
+    python3 -m pip install --user Electrum-4.5.5.tar.gz --break-system-packages || { \
+    echo "Something went wrong with PIP installation of Electrum." ; \
+    exit 1 ; \
+    }
+
+WORKDIR /home/parman/
+
 CMD tail -f /dev/null 
 # Need to run fix_openssl_repemd160
-
-
 #user should set number of cores to dedicate to docker container
